apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: oscargm40/client-service
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: oscargm40/comments-service
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: oscargm40/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: oscargm40/moderation-service
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: oscargm40/postservice
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: oscargm40/query-service
      context: query
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .